# Generated by Django 3.0.6 on 2020-05-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Acc_password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
