# Generated by Django 3.0.6 on 2020-05-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200519_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
