# Generated by Django 3.0.6 on 2020-05-29 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccID', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='get_time',
            new_name='getTime',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Chat_name',
            new_name='RoomName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='Acc_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='AccSent',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Chat',
            new_name='Room',
        ),
        migrations.DeleteModel(
            name='Chat_Acc',
        ),
        migrations.AddField(
            model_name='room_acc',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
